### ISSUE TITLE
Support left colon bem syntax

### ISSUE THREAD

**Issue by mgreter** [mgreter/sass2scss#26]
The following
```sass
.testing
  :margin
    :bottom 32px
    :foo
      :bar 1px
      :baz 2px
    :baz 3px
  :end 4px
```

Should result in
```css
.testing {
  margin-bottom: 32px;
  margin-foo-bar: 1px;
  margin-foo-baz: 2px;
  margin-baz: 3px;
  end: 4px; }
```

To acheive this we definitely need to keep track of the bem partial stack (to unwind it later). Indicators are if line starts with exactly one colon `:` followed by one identifier.

https://github.com/sass/libsass/issues/1781
https://github.com/sass/node-sass/issues/1300
