### ISSUE TITLE
Url in a property value taken as a comment

### ISSUE THREAD

**Issue by paazmaya** [mgreter/sass2scss#9]
Perhaps due to recent changes, or not, but currently the following Sass:

``` sass
@font-face
  font-family: 'Inder'
  font-style: normal
  font-weight: normal
  src: url('http://fonts/inder.eot?#iefix') format('embedded-opentype')
```

becomes SCSS:

``` scss
@font-face {
  font-family: 'Inder';
  font-style: normal;
  font-weight: normal;
  src: url('http:; }//fonts/inder.eot?#iefix') format('embedded-opentype')
```

Without the `//` part seems to work as one would expect, valid SCSS.

Perhaps for the comment check, there should be added exclusion if the `//` is immediately after with `:`?
